grounding_dino:
  config_path: /path/to/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py
  checkpoint_path: /path/to/groundingdino_swint_ogc.pth
  box_threshold: 0.4
  text_threshold: 0.25
sam:
  checkpoint_path: /path/to/sam_vit_h_4b8939.pth
  encoder_version: vit_h
checkpoint_step: 100
ontology:
  key:
    - "person"
  value:
    - "a human being"
data:
  image_dir: ./raw_data
  image_extensions: [".jpg", ".png", ".jpeg"]
annotations:
  min_image_area_percentage: 0.002
  max_image_area_percentage: 0.8
  approximation_percentage: 0.75
  root_path: ./dataset
  coco_annotations_path: annotations/annotations.json
  labels:
    set: ["train", "val", "test"]
logging_level: INFO